name: Build Iris

# For each push on all branches
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4.0.0

      - name: Set outputs
        id: vars
        #run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up JDK 17
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup build cache
        uses: actions/cache@v3.3.2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      
      - name: Gradle Permission
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build --full-stacktrace

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: Iris-${{ steps.vars.outputs.sha_short }}
          path: build/libs

      - name: Release Files
        uses: softprops/action-gh-release@v1
        with: 
          token: ${{ secrets.RELEASE_KEY }}
          files: |
            build/libs/*.jar
          tag_name: commit-${{ steps.vars.outputs.sha_short }}
          name: Iris [${{ steps.vars.outputs.sha_short }}]
          body: |
            Commit: ${{ steps.vars.outputs.sha_short }}
          generate_release_notes: true
        env:
          GITHUB_REPOSITORY: SirDank/Iris-AutoCompile
